openapi: 3.0.3

info:
  title: Github Gitlab Service API
  description: Service to fetch user info and repositories from GitHub and GitLab
  version: 1.0.0

servers:
  - url: http://localhost:8087/api
    description: Local server

paths:

  /users/{user}:

    get:
      summary: Get user with repositories.
      operationId: getUserByUsername
      description: Returns user with repositories.
      parameters:
        - $ref: '#/components/parameters/UserRequestParameters'
      responses:
        200:
          description: User with repositories has been fetched successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        404:
          $ref: '#/components/responses/NotFound'
        5XX:
          $ref: '#/components/responses/UnexpectedError'

components:

  parameters:

    UserRequestParameters:
      name: user
      in: path
      required: true
      description: User to fetch by username.
      schema:
        type: string
        description: Username.

  schemas:

    UserResponse:
      type: object
      description: Array of all events.
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/GitProperties'

    GitProperties:
      type: object
      description: Git properties.
      properties:
        source:
          type: string
          description: Git source (e.g., GitHub, GitLab).
        id:
          type: integer
          description: User ID in git source.
        username:
          type: string
          description: Username of the git user.
        lastUpdate:
          type: string
          description: Last update timestamp.
        repositories:
          type: array
          description: List of git repositories for the user.
          items:
            type: object
            properties:
              id:
                type: integer
                description: Repository ID.
              name:
                type: string
                description: Repository name.
            required:
              - id
              - name
      required:
        - source
        - id
        - username

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message

  responses:

    NotFound:
      description: "Resource not found."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    UnexpectedError:
      description: "Unexpected Error."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
