server:
  port: 8087

spring:
  application:
    name: github-gitlab-service
  datasource:
    url: jdbc:postgresql://localhost:5437/github_gitlab_service
    driverClassName: org.postgresql.Driver
    username: "postgres"
    password: "postgres"
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/main.xml
  mustache:
    check-template-location: false

logging:
  level:
    eu.profinit.githubgitlabservice: debug

openapi:
  base-path: /api/

git:
  gitlab:
    base-url: http://localhost:8086
    accept: application/json
  github:
    base-url: https://api.github.com
    accept: application/vnd.github+json

cache:
    ttl-seconds: 60
